### ISSUE TITLE
Runtime Update

### ISSUE THREAD

**Issue by Justinzobel** [flathub/org.kde.kmplayer#41]
Please consider upgrading to a Qt6 runtime if your application supports Qt6, or 5.15-2308 otherwise.

**Comment by tsdgeos** [comment]
Are you talking to yourself? :D   

https://github.com/flathub/org.kde.kmplayer/pull/35

**Comment by Justinzobel** [comment]
Quite often, yes. I did a bulk Issue creation for all apps on all EOL'd KDE runtimes.
